/**
 * Checking a cover file, as far as a file can honestly be checked.
 *
 * Covers are the loudest sales pain in the research and the one we cannot
 * build: *"Check the cover. Generated by AI? People will believe the whole book
 * is AI-generated"*, *"$1000 covers are a non-starter"*. The wall on the covers
 * page shows a writer the shelf they are joining. This is the other half —
 * whether the file itself will be refused.
 *
 * **What is here is mechanical, and that is the whole list.** Pixel dimensions,
 * the shape, the weight, and how much contrast the image has. A cover being
 * *good* is not measurable and this does not pretend otherwise; there is no
 * score, and the two questions that actually decide a cover's fate — is the
 * title readable at 60px, and does it look like its genre — are answered by
 * looking, which is what the wall is for.
 *
 * **The figures are Amazon KDP's published guidance**, held in named constants
 * so a change is one line and a failed test. As with the paperback numbers,
 * this does not replace the shop's own checker.
 */

/** KDP's minimum on the longest side, and what it recommends. */
export const MIN_LONG_EDGE = 1000;
export const IDEAL_WIDTH = 1600;
export const IDEAL_HEIGHT = 2560;

/** Height divided by width. KDP's recommended shape for an ebook cover. */
export const IDEAL_RATIO = 1.6;

/** KDP refuses a cover file larger than this. */
export const MAX_BYTES = 50 * 1024 * 1024;

export type CheckLevel = "problem" | "note";

export interface CoverFinding {
  id: string;
  level: CheckLevel;
  label: string;
  detail: string;
}

export interface CoverFacts {
  width: number;
  height: number;
  bytes: number;
  /**
   * Mean absolute deviation of pixel luminance, 0–1. A flat, low-contrast
   * image sits near zero. Optional: it costs a canvas read, and every other
   * check here works without one.
   */
  contrast?: number;
}

/**
 * Contrast below which a cover is likely to disappear against a shop's page.
 *
 * A convention rather than a finding, and it only ever produces a note — plenty
 * of excellent literary covers are three greys and a serif.
 */
const FLAT = 0.08;

export function checkCover(facts: CoverFacts): CoverFinding[] {
  const findings: CoverFinding[] = [];
  const { width, height, bytes } = facts;
  const longEdge = Math.max(width, height);
  const ratio = width > 0 ? height / width : 0;

  // ---- Things a shop refuses ----------------------------------------------

  if (longEdge < MIN_LONG_EDGE) {
    findings.push({
      id: "too-small",
      level: "problem",
      label: "Too small to upload",
      detail: `${width}×${height}. The longest side has to be at least ${MIN_LONG_EDGE}px, and ${IDEAL_WIDTH}×${IDEAL_HEIGHT} is what shops ask for.`,
    });
  }

  if (bytes > MAX_BYTES) {
    findings.push({
      id: "too-heavy",
      level: "problem",
      label: "Too large a file",
      detail: `${(bytes / 1024 / 1024).toFixed(1)}MB. The limit is 50MB — save it again at a lower JPEG quality rather than shrinking the picture.`,
    });
  }

  // ---- Things worth knowing ------------------------------------------------

  if (width > 0 && height > 0) {
    const off = Math.abs(ratio - IDEAL_RATIO);
    if (off > 0.15) {
      findings.push({
        id: "shape",
        level: "note",
        label: ratio < IDEAL_RATIO ? "Squarer than usual" : "Taller than usual",
        detail: `This is ${ratio.toFixed(2)}:1; shops set their thumbnails at about ${IDEAL_RATIO}:1. A cover of another shape is not refused — it is letterboxed, so it appears smaller than its neighbours in a list.`,
      });
    }
  }

  if (longEdge >= MIN_LONG_EDGE && longEdge < IDEAL_HEIGHT) {
    findings.push({
      id: "small-ish",
      level: "note",
      label: "Smaller than recommended",
      detail: `${width}×${height} will be accepted. ${IDEAL_WIDTH}×${IDEAL_HEIGHT} is what shops recommend, and it is what a reader on a high-resolution phone sees the difference in.`,
    });
  }

  if (facts.contrast !== undefined && facts.contrast < FLAT) {
    findings.push({
      id: "flat",
      level: "note",
      label: "Low contrast overall",
      detail:
        "It may disappear against a white shop page beside busier covers. Some very good literary covers are exactly this, so it is a thing to look at rather than a thing to fix.",
    });
  }

  return findings;
}

/**
 * Mean absolute deviation of luminance across sampled pixels, 0–1.
 *
 * Sampled rather than exhaustive: a 2560px cover is six million pixels and the
 * answer does not change past a few thousand. Takes raw RGBA, so the caller
 * owns the canvas and this stays pure and testable.
 */
export function contrastOf(pixels: Uint8ClampedArray, step = 4 * 37): number {
  const values: number[] = [];
  for (let i = 0; i < pixels.length; i += step) {
    // Rec. 601 luma — near enough for "is this flat", and cheap.
    const luma =
      (0.299 * pixels[i] + 0.587 * pixels[i + 1] + 0.114 * pixels[i + 2]) / 255;
    if (Number.isFinite(luma)) values.push(luma);
  }
  if (values.length === 0) return 0;
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  const deviation =
    values.reduce((sum, v) => sum + Math.abs(v - mean), 0) / values.length;
  return Math.round(deviation * 1000) / 1000;
}

/* -------------------------------------------------------------------------- */
/* Putting the shape right                                                     */
/* -------------------------------------------------------------------------- */

/**
 * The size a cover of the wrong shape becomes, without inventing a pixel.
 *
 * **Upscaling is deliberately not offered anywhere here**, and that is the
 * whole reason this is arithmetic rather than a slider. A 554×841 cover scaled
 * to 1600×2560 passes the shop's pixel check and looks worse doing it — the
 * interpolation cannot add detail that was never photographed, and the soft
 * result is the thing the trade press calls an amateur cover. A tool that
 * makes a warning disappear while making the book harder to sell has helped
 * nobody. So the only fix on offer is the one that is honestly available: put
 * the *shape* right, and leave the resolution question to be answered where it
 * can actually be answered, in the original artwork.
 *
 * Both modes draw the source at 1:1 — `crop` takes a sub-rectangle, `pad` lays
 * the whole image on a larger canvas — so neither resamples the artwork.
 *
 * `crop` trims the long edge and therefore *loses* picture, which on a cover is
 * usually a title or a byline near the edge; `pad` keeps everything and adds
 * bars. Neither is right in general, which is why the screen offers both and
 * shows what each one costs rather than picking for the writer.
 */
export interface Reshape {
  width: number;
  height: number;
  /** Pixels lost off the long edge (crop), or added as bars (pad). */
  changed: number;
  /** True when the result drops under what a shop will accept. */
  tooSmall: boolean;
}

export function reshape(
  width: number,
  height: number,
  mode: "crop" | "pad",
  ratio: number = IDEAL_RATIO,
): Reshape {
  const tall = height / width > ratio;
  let out: { width: number; height: number };

  if (mode === "crop") {
    // Trim whichever edge is too long, keeping the other whole.
    out = tall
      ? { width, height: Math.round(width * ratio) }
      : { width: Math.round(height / ratio), height };
  } else {
    // Grow the short edge instead, so every pixel of the artwork survives.
    out = tall
      ? { width: Math.round(height / ratio), height }
      : { width, height: Math.round(width * ratio) };
  }

  const changed =
    mode === "crop"
      ? tall
        ? height - out.height
        : width - out.width
      : tall
        ? out.width - width
        : out.height - height;

  return {
    ...out,
    changed: Math.abs(changed),
    tooSmall: Math.max(out.width, out.height) < MIN_LONG_EDGE,
  };
}

/**
 * The scaled size that covers the recommended 1600×2560, for the one fix that
 * *does* resample.
 *
 * **This is the exception to the rule above, and it is deliberate rather than a
 * lapse.** Everything else on this screen refuses to invent pixels; enlarging
 * invents every pixel it adds. It exists because a writer whose only file is
 * 1447×1087 has no other route to the size shops recommend, and because
 * refusing to do it did not stop them wanting it — it stopped them doing it
 * *here*, where the screen can at least say what the trade-off is.
 *
 * So the arithmetic returns `factor` as well as the size, and the screen says
 * it out loud: a factor above 1 means the result is interpolated and no sharper
 * than the original, whatever its pixel count claims.
 *
 * Scales to **cover** rather than to fit, so the frame fills and the writer
 * chooses which part survives — the same positioning the crop uses.
 */
export interface Enlarged {
  width: number;
  height: number;
  /** Rendered size of the artwork inside that frame. */
  drawWidth: number;
  drawHeight: number;
  /** Above 1 means pixels were invented. */
  factor: number;
}

export function enlarge(
  width: number,
  height: number,
  target: { width: number; height: number } = {
    width: IDEAL_WIDTH,
    height: IDEAL_HEIGHT,
  },
): Enlarged {
  const factor = Math.max(target.width / width, target.height / height);
  return {
    width: target.width,
    height: target.height,
    drawWidth: Math.round(width * factor),
    drawHeight: Math.round(height * factor),
    factor,
  };
}
