/**
 * How the shelf draws its books.
 *
 * Four modes, and the count is the design. The reference for the *menu* is
 * Windows Explorer's View, which is the right shape — a named list with a tick
 * on the current one, rather than a row of icon buttons nobody can read. Its
 * eight modes are not: List, Tiles and Content differ by a line of text each,
 * which is a menu that accumulated rather than one that was decided. These four
 * each answer a different question — show me the jackets, show me the usual,
 * fit them all on, tell me the numbers.
 *
 * **`layout`, never `view`.** `view` already means which *list* is showing —
 * active, favourite, archived, trashed — and it is threaded through the shelf,
 * the rail and the bulk-select rules. Two things called `view` in one component
 * is how the wrong one gets read a year later.
 */

export type ShelfLayout = "large" | "covers" | "small" | "list";

/** In menu order, with the word each one wears. */
export const SHELF_LAYOUTS: readonly { id: ShelfLayout; label: string }[] = [
  { id: "large", label: "Large covers" },
  { id: "covers", label: "Covers" },
  { id: "small", label: "Small covers" },
  { id: "list", label: "List" },
];

export const DEFAULT_SHELF_LAYOUT: ShelfLayout = "covers";

/**
 * The container's classes, **written out in full and never interpolated**.
 *
 * Tailwind v4 finds its utilities by scanning the source for complete strings.
 * A class assembled at runtime — `` `grid-cols-${n}` `` — is generated by
 * nothing, dropped from the stylesheet with no warning, and shows up as a mode
 * that silently does not change the column count. That failure is invisible in
 * review and in the type checker, which is why the whole set is spelled here.
 *
 * `list` is not a grid at all: one row per book, so the rows set their own
 * height rather than being squared into a cell.
 */
export function gridClassFor(layout: ShelfLayout): string {
  switch (layout) {
    case "large":
      return "grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3";
    case "covers":
      return "grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5";
    case "small":
      /* Three across on a phone rather than six: past that a jacket is 90px
         wide and the title under it wraps to four lines, which is denser
         without being more readable. The point of this mode is fitting a big
         shelf on a big screen. */
      return "grid grid-cols-3 gap-3 sm:grid-cols-4 lg:grid-cols-6 2xl:grid-cols-8";
    case "list":
      return "flex flex-col gap-2";
  }
}

/** Whether the books are drawn as jackets in a grid. */
export function isGrid(layout: ShelfLayout): boolean {
  return layout !== "list";
}

/**
 * The stored value, narrowed on the way in.
 *
 * `localStorage` holds whatever an older version left there, and a mode this
 * one does not know would reach `gridClassFor` and fall out of the switch.
 */
export function isShelfLayout(value: unknown): value is ShelfLayout {
  return SHELF_LAYOUTS.some((l) => l.id === value);
}
