import { describe, expect, it } from "vitest";
import {
  DEFAULT_SHELF_LAYOUT,
  gridClassFor,
  isGrid,
  isShelfLayout,
  resultsGridClass,
  SHELF_LAYOUTS,
  type ShelfLayout,
} from "@/lib/shelf-layout";

describe("SHELF_LAYOUTS", () => {
  /**
   * **The test that earns its place.** Add a mode to the list, forget the
   * switch, and the new entry falls through `gridClassFor` returning
   * `undefined` — a menu item that renders an unstyled column of books rather
   * than throwing. Nothing else in the app would notice.
   */
  it("gives every listed mode a container class", () => {
    for (const { id } of SHELF_LAYOUTS) {
      const cls = gridClassFor(id);
      expect(cls, `no classes for "${id}"`).toBeTruthy();
      expect(cls.length).toBeGreaterThan(0);
    }
  });

  it("names every mode", () => {
    for (const { id, label } of SHELF_LAYOUTS) {
      expect(label, `no label for "${id}"`).toBeTruthy();
    }
  });

  it("has no duplicate modes", () => {
    const ids = SHELF_LAYOUTS.map((l) => l.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("offers the default as one of its own options", () => {
    expect(SHELF_LAYOUTS.some((l) => l.id === DEFAULT_SHELF_LAYOUT)).toBe(true);
  });
});

describe("gridClassFor", () => {
  /**
   * Tailwind v4 scans source for complete class strings. One assembled at
   * runtime is generated by nothing and dropped from the stylesheet in
   * silence, so the mode would look identical to the one before it. These
   * assertions are the cheap standing guard against somebody "tidying" the map
   * into a template literal.
   */
  it("writes its column counts out in full", () => {
    expect(gridClassFor("covers")).toContain("sm:grid-cols-3");
    expect(gridClassFor("covers")).toContain("lg:grid-cols-4");
    expect(gridClassFor("large")).toContain("sm:grid-cols-2");
    expect(gridClassFor("small")).toContain("lg:grid-cols-6");
  });

  /*
   * **The default mode stops at four, and nothing else would notice it
   * moving.** It ran to five at `2xl`, which on a wide monitor is a jacket
   * narrow enough for the title under it to wrap — the job `small` already
   * does. A fifth column is one class away from coming back, and it would come
   * back on the mode every writer sees first.
   */
  it("keeps the default mode at four columns across", () => {
    const covers = gridClassFor(DEFAULT_SHELF_LAYOUT);
    expect(covers).toContain("lg:grid-cols-4");
    expect(covers).not.toContain("grid-cols-5");
    expect(covers).not.toContain("grid-cols-6");
  });

  it("keeps every grid mode on a different column count", () => {
    const grids: ShelfLayout[] = ["large", "covers", "small"];
    const classes = grids.map(gridClassFor);
    expect(new Set(classes).size).toBe(grids.length);
  });

  // Three across on a phone, not six — past that the titles wrap to four lines.
  it("does not crowd the small mode on a narrow screen", () => {
    expect(gridClassFor("small")).toContain("grid-cols-3");
    expect(gridClassFor("small")).not.toContain(" grid-cols-6");
  });

  it("does not lay the list out as a grid", () => {
    expect(gridClassFor("list")).not.toContain("grid-cols");
    expect(gridClassFor("list")).toContain("flex");
  });
});

describe("isGrid", () => {
  it("is true for the three cover modes and false for the list", () => {
    expect(isGrid("large")).toBe(true);
    expect(isGrid("covers")).toBe(true);
    expect(isGrid("small")).toBe(true);
    expect(isGrid("list")).toBe(false);
  });
});

describe("isShelfLayout", () => {
  it("accepts every mode it offers", () => {
    for (const { id } of SHELF_LAYOUTS) expect(isShelfLayout(id)).toBe(true);
  });

  /* `localStorage` holds whatever an older version left there. */
  it("refuses anything else", () => {
    expect(isShelfLayout("tiles")).toBe(false);
    expect(isShelfLayout("")).toBe(false);
    expect(isShelfLayout(undefined)).toBe(false);
    expect(isShelfLayout(null)).toBe(false);
    expect(isShelfLayout(3)).toBe(false);
    expect(isShelfLayout({ id: "covers" })).toBe(false);
  });
});

describe("resultsGridClass", () => {
  /* The same guard `gridClassFor` carries: add a mode to `SHELF_LAYOUTS`,
     forget this switch, and the new entry falls through returning `undefined`
     — a menu item that draws an unstyled column of search results rather than
     throwing. */
  it("gives every listed mode a container class", () => {
    for (const { id } of SHELF_LAYOUTS) {
      expect(resultsGridClass(id), `no classes for "${id}"`).toBeTruthy();
    }
  });

  /*
   * **Container queries, not breakpoints, and this is the test that says so.**
   *
   * Both search screens sit inside an `@container` and open at about half a
   * window in the roadmap's panel. A `lg:` class there asks how wide the
   * *window* is, which is a question about the wrong box — six columns drawn
   * into a half-width sheet. The classes look almost identical either way, so
   * nothing but this would notice one being copied across from `gridClassFor`.
   */
  it("measures its container rather than the window", () => {
    for (const { id } of SHELF_LAYOUTS) {
      const cls = resultsGridClass(id);
      expect(cls, id).not.toMatch(/(^| )(sm|md|lg|xl|2xl):/);
    }
    expect(resultsGridClass("covers")).toContain("@lg:grid-cols-4");
    expect(resultsGridClass("small")).toContain("@lg:grid-cols-6");
  });

  /*
   * **Five, where the shelf's own Covers stops at four**, and the difference is
   * deliberate rather than drift: a shelf book carries a word count and a ⋯
   * menu under it, a search result carries a jacket and two lines of small
   * print. Pinned because the two functions look alike enough that somebody
   * tidying them together would make one of them wrong.
   */
  it("puts five search results across at the top end", () => {
    expect(resultsGridClass("covers")).toContain("@4xl:grid-cols-5");
    expect(gridClassFor("covers")).not.toContain("grid-cols-5");
  });

  it("keeps every grid mode on a different column count", () => {
    const grids: ShelfLayout[] = ["large", "covers", "small"];
    expect(new Set(grids.map(resultsGridClass)).size).toBe(grids.length);
  });

  it("does not lay the list out as a grid", () => {
    expect(resultsGridClass("list")).not.toContain("grid-cols");
    expect(resultsGridClass("list")).toContain("flex");
  });
});
