/**
 * How the shelf draws its books.
 *
 * Four modes, and the count is the design. The reference for the *menu* is
 * Windows Explorer's View, which is the right shape — a named list with a tick
 * on the current one, rather than a row of icon buttons nobody can read. Its
 * eight modes are not: List, Tiles and Content differ by a line of text each,
 * which is a menu that accumulated rather than one that was decided. These four
 * each answer a different question — show me the jackets, show me the usual,
 * fit them all on, tell me the numbers.
 *
 * **`layout`, never `view`.** `view` already means which *list* is showing —
 * active, favourite, archived, trashed — and it is threaded through the shelf,
 * the rail and the bulk-select rules. Two things called `view` in one component
 * is how the wrong one gets read a year later.
 */

export type ShelfLayout = "large" | "covers" | "small" | "list";

/** In menu order, with the word each one wears. */
export const SHELF_LAYOUTS: readonly { id: ShelfLayout; label: string }[] = [
  { id: "large", label: "Large covers" },
  { id: "covers", label: "Covers" },
  { id: "small", label: "Small covers" },
  { id: "list", label: "List" },
];

export const DEFAULT_SHELF_LAYOUT: ShelfLayout = "covers";

/**
 * The container's classes, **written out in full and never interpolated**.
 *
 * Tailwind v4 finds its utilities by scanning the source for complete strings.
 * A class assembled at runtime — `` `grid-cols-${n}` `` — is generated by
 * nothing, dropped from the stylesheet with no warning, and shows up as a mode
 * that silently does not change the column count. That failure is invisible in
 * review and in the type checker, which is why the whole set is spelled here.
 *
 * `list` is not a grid at all: one row per book, so the rows set their own
 * height rather than being squared into a cell.
 */
/**
 * **Container queries, not viewport ones, and that is the whole of the change.**
 *
 * These read `sm:` / `lg:` / `2xl:` — the *window* — so collapsing the sidebar
 * did nothing to them: the window had not moved. The column beside the rail is
 * what actually changes width, and `@`-prefixed variants ask that instead. The
 * shelf's grid wrapper carries the `@container` they measure against.
 *
 * **The counts themselves are unchanged**, and Covers deliberately does not
 * gain a column here. Collapsing the rail moves the *results* grid to six, and
 * the temptation is to move this one with it — but the reason Covers stops at
 * four is about the jacket, not about the window: past four the title under it
 * wraps, which is the job `small` already does. `shelf-layout.test.ts` pins it,
 * and it caught exactly this edit being made.
 */
export function gridClassFor(layout: ShelfLayout): string {
  switch (layout) {
    case "large":
      return "grid grid-cols-1 gap-5 @sm:grid-cols-2 @lg:grid-cols-3";
    case "covers":
      /* **Four across at the widest, not five.** It ran to `2xl:grid-cols-5`,
         and on a wide monitor that is a jacket narrow enough that the title
         under it wraps — which is what `small` is *for*. This is the default
         mode, so it is the one that has to be the comfortable answer rather
         than the dense one; anybody who wants more books on the screen has
         two modes below it that say so. */
      return "grid grid-cols-2 gap-4 @sm:grid-cols-3 @lg:grid-cols-4";
    case "small":
      /* Three across on a phone rather than six: past that a jacket is 90px
         wide and the title under it wraps to four lines, which is denser
         without being more readable. The point of this mode is fitting a big
         shelf on a big screen. */
      return "grid grid-cols-3 gap-3 @sm:grid-cols-4 @lg:grid-cols-6 @6xl:grid-cols-8";
    case "list":
      return "flex flex-col gap-2";
  }
}

/**
 * The same four modes for a wall of *found* books — the comps shelf and the
 * title check's matches.
 *
 * **Container queries, not breakpoints, and that is the whole reason this is a
 * second function rather than a parameter on the first.** Both search screens
 * sit inside an `@container`: they run the full width of a tool page, about
 * half of it in the roadmap's panel, and a dashboard column wide in the
 * Research area. A `lg:` class asks how big the *window* is, which in a panel
 * is a question about the wrong box — it would draw six columns into a
 * half-width sheet. The shelf has no such problem and keeps the viewport
 * variants it has always had.
 *
 * Written out in full for the same reason `gridClassFor` is: Tailwind v4 finds
 * its utilities by scanning source for complete strings, so a class assembled
 * at runtime is generated by nothing and silently missing from the stylesheet.
 *
 * The counts are one step denser than the shelf's at each mode. A search result
 * is a jacket, a title and a line of small print; a shelf book is somebody's
 * own manuscript with its word count and its menu, and wants more room.
 */
export function resultsGridClass(layout: ShelfLayout): string {
  switch (layout) {
    case "large":
      return "grid grid-cols-1 gap-x-5 gap-y-7 @sm:grid-cols-2 @lg:grid-cols-3";
    case "covers":
      /* **Five at the top end, where the shelf's own Covers stops at four.**
         Not an inconsistency: a shelf book is somebody's manuscript with its
         word count and its ⋯ menu under it, and a search result is a jacket
         and two lines of small print. The second fits five to a row at the
         width these screens actually run at, and a wall of comps is read by
         sweeping it rather than by reading each entry. `@4xl` is 56rem of
         *container*, not window — see the note above. */
      return "grid grid-cols-2 gap-x-4 gap-y-6 @sm:grid-cols-3 @lg:grid-cols-4 @4xl:grid-cols-5 @6xl:grid-cols-6";
    case "small":
      /* Three on a phone rather than six, exactly as the shelf argues: past
         that a jacket is 90px wide and the title under it wraps to four lines,
         which is denser without being more readable. */
      return "grid grid-cols-3 gap-x-3 gap-y-5 @sm:grid-cols-4 @lg:grid-cols-6 @2xl:grid-cols-8";
    case "list":
      return "flex flex-col gap-1";
  }
}

/** Whether the books are drawn as jackets in a grid. */
export function isGrid(layout: ShelfLayout): boolean {
  return layout !== "list";
}

/**
 * The stored value, narrowed on the way in.
 *
 * `localStorage` holds whatever an older version left there, and a mode this
 * one does not know would reach `gridClassFor` and fall out of the switch.
 */
export function isShelfLayout(value: unknown): value is ShelfLayout {
  return SHELF_LAYOUTS.some((l) => l.id === value);
}
